### ISSUE TITLE
Create `tags`

### ISSUE THREAD

**Issue by nobe4** [nobe4/gh-not#197]
Tags should mimic what the "filter" does on the GitHub UI:

![Image](https://github.com/user-attachments/assets/e90ae3af-27bf-4637-a65f-73167aa7541d)

In the config, they should be defined via filters like for the `rules`:

```yaml
groups:
  - name: created by me
    filters: [".subject.author == nobe4"]
  - name: only recent discussions
    filters: 
        - .subject.type == "discussions"
        - .updated_at < now - 2
```

From the CLI and the REPL, it should be possible to target specific tags.

- [x] How to store the tags? => in the `Meta`
- [x] Should they be cached? => not for now
