### ISSUE TITLE
Not getting any notifications

### ISSUE THREAD

**Issue by alondahari** [nobe4/gh-not#23]
I installed as an extension to gh and I'm not getting any notifications after running `gh not sync` and `gh not list`. My inbox is full and `gh api notifications` work, as well as `gh status`.

My config:

```
---

rules:
  - name: showcasing conditionals
    action: debug
    # Filters are run one after the other, like they are joined by `and`.
    # Having `or` can be done via `(cond1) or (cond2) or ...`.
    filters:
      - .author.login == "dependabot[bot]"
      - >
        (.subject.title | contains("something unimportant")) or
        (.subject.title | contains("something already done"))

  - name: ignore ci failures for the current repo
    action: done
    filters:
      - .repository.full_name == "github/github"
      - .reason == "ci_activity"

  - name: list important notifications
    action: read
    filters:
      - .repository.full_name == "github/github"
```

gh cli v2.50.0

![Image](https://github.com/nobe4/gh-not/assets/5546798/bba499ec-c453-4905-a9d2-f594caf1e94a)
