### ISSUE TITLE
`config --init` writes everything in `config`

### ISSUE THREAD

**Issue by nobe4** [nobe4/gh-not#75]
```
gh not config -R | head
Config sourced from: 

data:
    cache:
        path: /Users/nobe4/.local/state/gh-not/cache.json
        ttl_in_hours: 0
    endpoint:
        all: true
        max_retry: 0
        max_page: 0
```

It should only marshal the content of `config.Data`, not `config`.
