### ISSUE TITLE
Enhanced Filter Documentation 📚

### ISSUE THREAD

**Issue by GrantBirki** [nobe4/gh-not#86]
# Filter Documentation

This issue requests _enhanced_ filter documentation. Perhaps its just me being 🥔 🧠 but I am struggling to figure out how to get the following filter working:

```yaml
- name: ignore noisy review requests
    action: done
    filters:
      - (.repository.full_name == "org/repo1" or .repository.full_name == "org/repo2")
      - .reason == "review_requested"
```

I have tried a few variations of this filter:

- Attempt 1:
  
  ```yaml
  (.repository.full_name == "org/repo1" or .repository.full_name == "org/repo2")
  ```

- Attempt 2:

  ```yaml
  filters:
      - >
        (.repository.full_name == "org/repo1") or
        (.repository.full_name == "org/repo2") and
        .reason == "review_requested"
  ```

I have also tested `review-requested` instead of `review_requested` without luck as well.

Here is what I'm trying to get my filter to do in plain English:

> _Mark notifications as **done** that are from `org/repo1`, or `org/repo2` repos with the `review_requested` status_.
